name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cke:
    name: Build projects from "cke" directory
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    defaults:
      run:
        working-directory: ${{github.workspace}}/cke
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build project
      run: cmake --build build --config ${{matrix.build_type}}

  matura:
    name: Build projects from "matura" directory
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    defaults:
      run:
        working-directory: ${{github.workspace}}/matura
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build project
      run: cmake --build build --config ${{matrix.build_type}}
